version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: assessments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  web:
    build: .
    user: root
    working_dir: /app/app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/app/static
      - media_volume:/app/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here-change-in-production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/assessments_db
      - REDIS_URL=redis://redis:6379/0
      - PII_ENCRYPTION_KEY=your-fernet-key-here-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,web,*.suaapp.local
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        mkdir -p /app/app/logs &&
        chown -R appuser:appuser /app/app/logs &&
        while ! pg_isready -h db -p 5432 -U postgres; do
          echo 'Waiting for database...'
          sleep 2
        done &&
        echo 'Database is up - executing migrations' &&
        python manage.py makemigrations accounts &&
        python manage.py migrate accounts &&
        python manage.py migrate account &&
        python manage.py migrate &&
        python manage.py seed_all &&
        echo 'Starting Gunicorn server' &&
        gunicorn --bind 0.0.0.0:8000 --workers 3 --reload core.wsgi:application
      "

  worker:
    build: .
    user: root
    working_dir: /app/app
    volumes:
      - .:/app
      - media_volume:/app/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here-change-in-production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/assessments_db
      - REDIS_URL=redis://redis:6379/0
      - PII_ENCRYPTION_KEY=your-fernet-key-here-change-in-production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        mkdir -p /app/app/logs &&
        chown -R appuser:appuser /app/app/logs &&
        while ! pg_isready -h db -p 5432 -U postgres; do
          echo 'Waiting for database...'
        done &&
      "

  beat:
    build: .
    user: root
    working_dir: /app/app
    volumes:
      - .:/app
      - media_volume:/app/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here-change-in-production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/assessments_db
      - REDIS_URL=redis://redis:6379/0
      - PII_ENCRYPTION_KEY=your-fernet-key-here-change-in-production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        mkdir -p /app/app/logs &&
        chown -R appuser:appuser /app/app/logs &&
        while ! pg_isready -h db -p 5432 -U postgres; do
          echo 'Waiting for database...'
          sleep 2
        done &&
        echo 'Database is up - starting Celery beat' &&
        cd /usr/src/app/app &&
        PYTHONPATH=. celery -A core.celery beat -l info
        cd /usr/src/app/app &&
        PYTHONPATH=. celery -A core.celery worker -l info
       "
volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: